### ISSUE TITLE
Nothing...

### ISSUE THREAD

**Issue by PersonForever** [leoschur/blender-lithtech-dat-import#1]

**Comment by ManevogerKrCode** [comment]
This plugin can import the UV of the PhysicsData, you can take a look

**Comment by ManevogerKrCode** [comment]
github.com/270899colin/Lithtech-Unity-Importer

**Comment by ManevogerKrCode** [comment]
github.com/AkvenJan/LithTech-DAT-UV-Vectors-Upscaler
